spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}

server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}
  forward-headers-strategy: native
  servlet:
    session:
      timeout: 1440m
      cookie:
        max-age: 1440m
        name: SID
        http-only: true
        secure: true

kakao:
  javascript:
    key: 1ce0abfad90d9a6d9d56d9cd4892ea1d